### PR TITLE
Update people.txt

### PR DESCRIPTION
**Pull request by SanAndreaP**
Can I add myself to this list of people? :D :lollipop:

### CODE REVIEW

**Comment by marysaka** [comment]
If you become more famous, I will add you.

**Comment by SanAndreaP** [comment]
Alright.

I just want to ask: what counts as "more famous"?

**Comment by Drullkus** [comment]
You've never heard of Clay Solders?! It's a gem! :P

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280625-clay-soldiers-mod-v-2-0-0-beta-2

**Comment by marysaka** [comment]
Oh nop xD. I will try it so let's merge and restart the generator!

PS : Sorry again but I don't want to add random people

**Comment by Drullkus** [comment]
I had the idea you didn't want to add random people, lol

**Pull request merged**
